# src/libc/pc_hw/co80/nec98/makefile
TOP=../../..

SRC += conio_n.c
SRC += scattr_n.c
SRC += scclr_n.c
SRC += sccols_n.c
SRC += scgetc_n.c
SRC += scgetchn.c
SRC += scmode_n.c
SRC += scputc_n.c
SRC += scputs_n.c
SRC += scretr_n.c
SRC += scrows_n.c
SRC += scsetc_n.c
SRC += scupd_n.c
SRC += scupdl_n.c
SRC += scvbel_n.c

include $(TOP)/../makefile.inc

