# src/libc/bios/ibmpc/makefile
TOP=../..

SRC += b_time_i.c
SRC += bioscomi.c
SRC += biosdski.c
SRC += bioseq_i.c
SRC += bioskeyi.c
SRC += biosmemi.c
SRC += biosprni.c
SRC += biostm_i.c
#SRC += 

include $(TOP)/../makefile.inc
