# src/libc/pc_hw/co80/ibmpc/makefile
TOP=../../..

SRC += conio_i.c
SRC += scclr_i.c
SRC += sccols_i.c
SRC += scgetc_i.c
SRC += scgetchi.c
SRC += scmode_i.c
SRC += scputc_i.c
SRC += scputs_i.c
SRC += scretr_i.c
SRC += scrows_i.c
SRC += scsetc_i.c
SRC += scupd_i.c
SRC += scupdl_i.c
SRC += scvbel_i.c

include $(TOP)/../makefile.inc

