# src/libc/pc_hw/co80/common/makefile
TOP=../../..

SRC += conio.c

SRC += scfuncs.c
SRC += scclear.c
SRC += sccols.c
SRC += scgetc.c
SRC += scgetch.c
SRC += scmode.c
SRC += scputc.c
SRC += scputs.c
SRC += scretr.c
SRC += scrows.c
SRC += scsetc.c
SRC += scupdate.c
SRC += scupdl.c
SRC += scvbell.c

include $(TOP)/../makefile.inc

