# src/libc/bios/nec98/makefile
TOP=../..

SRC += b_time_n.c
SRC += bioscomn.c
SRC += biosdskn.c
SRC += bioseq_n.c
SRC += bioskeyn.c
SRC += biosmemn.c
SRC += biosprnn.c
SRC += biostm_n.c
#SRC += 

include $(TOP)/../makefile.inc
